export default Object.freeze({
  VISIT_STATUS_ACCEPTED: "ACCEPTED",
  VISIT_STATUS_PENDING: "PENDING",
  VISIT_STATUS_DECLINED: "DECLINED",
  SEMESTER_CODE_AY1819_1: "AY1819-1",
  TEST_FACULTY_ID: "yncas"
});
