query findFaculty($faculty_id: String) {
  faculty(where: {id: {_eq: $faculty_id}}) {
    email
    id
    name
  }
}

mutation update_visit_response($visit_id: Int!, $visit_status: String!, $time_responded: timestamptz!, $response_msg: String) {
  update_visit_by_pk(pk_columns: {id: $visit_id}, _set: {time_responded: $time_responded, visit_status: $visit_status,     response_msg: $response_msg}) {
    time_responded
    visit_status
    response_msg
  }
}

query get_seminars_with_visits_by_time_requested($faculty_id: String, $semester_code: String) {
  seminar(where: {course_group: {faculty_id: {_eq: $faculty_id}}, _and: {semester_code: {_eq: $semester_code}}}) {
    title
    start
    module_code
    location_code
    location {
      full_name
    }
    date
    desc
    end
    id
    is_open
    semester_code
    group_code
    visitor_capacity
    visits(order_by: {time_requested: desc}) {
      id
      is_archived
      is_cancelled
      request_msg
      response_msg
      time_requested
      time_responded
      visit_status
      visitor_id
      visitor {
        email
        id
        name
        is_active
      }
    }
    course_group {
      course {
        title
      }
    }
  }
}

# query get_visit_status($visit_id:Int){
#   visit_by_pk(id: $visit_id){
#     visit_status
#     time_responded
#   }
# }