query searchSeminarsByFilters(
  $search_keyword: String!
  $faculty_name: String!
  $start_date: date!
  $end_date: date!
  $start_time: time!
  $end_time: time!
  $visitor_id: String
  $semester_code: String
  $teaching_modes: [String!]
  $include_cc_lectures: String!
) {
  seminar(
    where: {
      _and: [
        {
          _or: [
            { course_group: { course: { title: { _ilike: $search_keyword } } } }
            { course_group: { faculty: { name: { _ilike: $search_keyword } } } }
            {
              course_group: {
                course: {
                  tagged_as: { tag_label: { _ilike: $search_keyword } }
                }
              }
            }
          ]
        }
        { course_group: { faculty: { name: { _similar: $faculty_name } } } }
        { teaching_mode: { _in: $teaching_modes } }
        { date: { _gte: $start_date } }
        { date: { _lte: $end_date } }
        { start: { _gte: $start_time } }
        { end: { _lte: $end_time } }
        { semester_code: { _eq: $semester_code } }
        { group_code: { _similar: $include_cc_lectures } }
      ]
    }
    order_by: { date: asc, start: asc }
  ) {
    id
    date
    start
    end
    title
    is_open
    module_code
    group_code
    semester_code
    teaching_mode
    desc
    location {
      code
      full_name
    }
    course_group {
      id
      course_group_desc
      is_open
      syllabus
      notes
      faculty {
        id
        name
        email
        is_active
        has_consented
        profilePic
      }
      course {
        desc
        id
        title
        tagged_as {
          tag_label
        }
      }
    }
    visitor_capacity
    visits(where: { visitor_id: { _eq: $visitor_id } }) {
      id
      visit_status
      is_cancelled
      request_msg
      response_msg
      time_requested
      time_responded
    }
    visits_aggregate(
      distinct_on: id
      where: { visit_status: { _eq: "ACCEPTED" } }
    ) {
      aggregate {
        count
      }
    }
  }
}

query searchSeminarsByFiltersWithTags(
  $search_keyword: String!
  $faculty_name: String!
  $start_date: date!
  $end_date: date!
  $start_time: time!
  $end_time: time!
  $selected_tags: [String!]
  $visitor_id: String
  $semester_code: String
  $teaching_modes: [String!]
  $include_cc_lectures: String!
) {
  seminar(
    where: {
      _and: [
        {
          _or: [
            { course_group: { course: { title: { _ilike: $search_keyword } } } }
            { course_group: { faculty: { name: { _ilike: $search_keyword } } } }
            {
              course_group: {
                course: {
                  tagged_as: { tag_label: { _ilike: $search_keyword } }
                }
              }
            }
          ]
        }
        { course_group: { faculty: { name: { _similar: $faculty_name } } } }
        { teaching_mode: { _in: $teaching_modes } }
        { date: { _gte: $start_date } }
        { date: { _lte: $end_date } }
        { start: { _gte: $start_time } }
        { end: { _lte: $end_time } }
        {
          course_group: {
            course: { tagged_as: { tag_label: { _in: $selected_tags } } }
          }
        }
        { semester_code: { _eq: $semester_code } }
        { group_code: { _similar: $include_cc_lectures } }
      ]
    }
    order_by: { date: asc, start: asc }
  ) {
    id
    date
    start
    end
    title
    is_open
    module_code
    group_code
    semester_code
    teaching_mode
    location {
      code
      full_name
    }
    course_group {
      id
      course_group_desc
      is_open
      syllabus
      notes
      faculty {
        id
        name
        email
        is_active
        has_consented
        profilePic
      }
      course {
        id
        title
        tagged_as {
          tag_label
        }
      }
    }
    visitor_capacity
    visits(where: { visitor_id: { _eq: $visitor_id } }) {
      id
      visit_status
      is_cancelled
      request_msg
      response_msg
      time_requested
      time_responded
    }
    visits_aggregate(
      distinct_on: id
      where: { visit_status: { _eq: "ACCEPTED" } }
    ) {
      aggregate {
        count
      }
    }
  }
}

query searchOpenSeminarsByFilters(
  $search_keyword: String!
  $faculty_name: String!
  $start_date: date!
  $end_date: date!
  $start_time: time!
  $end_time: time!
  $visitor_id: String
  $semester_code: String
  $teaching_modes: [String!]
  $include_cc_lectures: String!
) {
  seminar(
    where: {
      _and: [
        {
          _or: [
            { course_group: { course: { title: { _ilike: $search_keyword } } } }
            { course_group: { faculty: { name: { _ilike: $search_keyword } } } }
            {
              course_group: {
                course: {
                  tagged_as: { tag_label: { _ilike: $search_keyword } }
                }
              }
            }
          ]
        }
        { course_group: { faculty: { name: { _similar: $faculty_name } } } }
        { teaching_mode: { _in: $teaching_modes } }
        { date: { _gte: $start_date } }
        { date: { _lte: $end_date } }
        { start: { _gte: $start_time } }
        { end: { _lte: $end_time } }
        { semester_code: { _eq: $semester_code } }
        { group_code: { _similar: $include_cc_lectures } }
        { course_group: { faculty: { has_consented: { _eq: true } } } }
        { course_group: { faculty: { is_active: { _eq: true } } } }
        { course_group: { is_open: { _eq: true } } }
        { is_open: { _eq: true } }
      ]
    }
  ) {
    id
    date
    start
    end
    title
    is_open
    module_code
    group_code
    semester_code
    teaching_mode
    desc
    location {
      code
      full_name
    }
    course_group {
      id
      course_group_desc
      is_open
      faculty {
        id
        name
        email
        is_active
        has_consented
      }
      course {
        desc
        id
        title
        tagged_as {
          tag_label
        }
      }
    }
    visitor_capacity
    visits(where: { visitor_id: { _eq: $visitor_id } }) {
      id
      visit_status
      is_cancelled
      request_msg
      response_msg
      time_requested
      time_responded
    }
    visits_aggregate(
      distinct_on: id
      where: { visit_status: { _eq: "ACCEPTED" } }
    ) {
      aggregate {
        count
      }
    }
  }
}

query searchOpenSeminarsByFiltersWithTags(
  $search_keyword: String!
  $faculty_name: String!
  $start_date: date!
  $end_date: date!
  $start_time: time!
  $end_time: time!
  $selected_tags: [String!]
  $visitor_id: String
  $semester_code: String
  $teaching_modes: [String!]
  $include_cc_lectures: String!
) {
  seminar(
    where: {
      _and: [
        {
          _or: [
            { course_group: { course: { title: { _ilike: $search_keyword } } } }
            { course_group: { faculty: { name: { _ilike: $search_keyword } } } }
            {
              course_group: {
                course: {
                  tagged_as: { tag_label: { _ilike: $search_keyword } }
                }
              }
            }
          ]
        }
        { course_group: { faculty: { name: { _similar: $faculty_name } } } }
        { teaching_mode: { _in: $teaching_modes } }
        { date: { _gte: $start_date } }
        { date: { _lte: $end_date } }
        { start: { _gte: $start_time } }
        { end: { _lte: $end_time } }
        {
          course_group: {
            course: { tagged_as: { tag_label: { _in: $selected_tags } } }
          }
        }
        { semester_code: { _eq: $semester_code } }
        { group_code: { _similar: $include_cc_lectures } }
        { course_group: { faculty: { has_consented: { _eq: true } } } }
        { course_group: { faculty: { is_active: { _eq: true } } } }
        { course_group: { is_open: { _eq: true } } }
        { is_open: { _eq: true } }
      ]
    }
  ) {
    id
    date
    start
    end
    title
    is_open
    module_code
    group_code
    semester_code
    teaching_mode
    location {
      code
      full_name
    }
    course_group {
      id
      course_group_desc
      is_open
      faculty {
        id
        name
        email
        is_active
        has_consented
      }
      course {
        id
        title
        tagged_as {
          tag_label
        }
      }
    }
    visitor_capacity
    visits(where: { visitor_id: { _eq: $visitor_id } }) {
      id
      visit_status
      is_cancelled
      request_msg
      response_msg
      time_requested
      time_responded
    }
    visits_aggregate(
      distinct_on: id
      where: { visit_status: { _eq: "ACCEPTED" } }
    ) {
      aggregate {
        count
      }
    }
  }
}
